name: genius_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - google_fonts/montserrat_alternates/
